#!/bin/bash

# Convert CR2 CANON RAW format to different formats
input_dir="${1}"
input_list=$(echo ${2} | tr "[]" "()" | tr "," " ")
output_dir="${3}"
output_format="${4}"

CR2toX() {
    #parameters:
    #1) input directory
    #2) list of files to convert
    #3) output directory
    #4) output format

    files_total=$(ls "${1}"/*.CR2 | wc -l)
    printf "Number of CR2 files to convert into ${4}: ${files_total}\n"
    printf "\n"

    file_counter=1
    files=${2}

    for i in "${files[@]}" 
        do 
            printf "\r ${file_counter} of ${files_total}\n"        
            base=$(basename ${i} .CR2)
            if [[ "${4}" == "jpeg" ]]; then
                sips -s format ${4} $i --out ${3}/"${base}.jpg"
            else
                sips -s format ${4} $i --out ${3}/"${base}.${4}"
            fi
            ((file_counter++))
        done
    printf "\n"
}

### Main

printf "\n --> Converting CR2 files to ${output_format}\n"
printf "\n"

CR2toX "${input_dir}" "$input_list" "${output_dir}" "${output_format}"

