#!/bin/bash

# Convert CR2 CANON RAW format to different formats
#parameters:
#1) input directory
#2) list of files to convert
#3) output directory
#4) output format

input_dir="${1}"
input_list=${2}
output_dir="${3}"
output_format="${4}"


## Main

printf "\n --> Converting CR2 files to ${output_format}\n"
printf "\n"

files_total=$(ls "${input_dir}"/*.CR2 | wc -l)
printf "Number of CR2 files to convert into ${output_format}: ${files_total}\n"
printf "\n"

file_counter=1

for i in ${input_list[@]} 
    do 
        printf "\r ${file_counter} of ${files_total}\n"
        sips -s format ${output_format} $i --out ${output_dir}
        ((file_counter++))
    done
printf "\n"

